---

- hosts: all
  vars:
    username_on_the_host: "{{ lookup('env','USER') }}"
  
  roles:
    - role: ssh
    - role: docker
      become: true

  tasks:
    - name: Current user can sudo without password
      ansible.builtin.copy:
        content: "{{username_on_the_host}} ALL=(ALL:ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/ftassi
