---

- hosts: localhost
  connection: local
  vars:
    username_on_the_host: "{{ lookup('env','USER') }}"
  tasks:
    - name: Install flatpak
      become: true
      ansible.builtin.apt:
        pkg:
        - flatpak

    - name: Install 1password
      community.general.flatpak:
        name: https://downloads.1password.com/linux/flatpak/1Password.flatpakref
        state: present
        method: user

    - name: Install packages from flathub
      community.general.flatpak:
        state: present
        method: user
        name:
          - org.mozilla.firefox
          - com.google.Chrome
          - com.slack.Slack
          - com.usebottles.bottles
