- name: Download aws-cli installer
  ansible.builtin.unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: yes

- name: Install aws-cli
  ansible.builtin.shell:
    chdir: /tmp/aws
    cmd: ./install --bin-dir ~/opt/bin --install-dir ~/opt/aws-cli --update
