- name: Install packages required to setup dotfiles
  become: true
  ansible.builtin.apt:
    pkg:
    - git
    - git-crypt
    - stow

- name: Copy git crypt key
  ansible.builtin.copy:
    src: files/.git-crypt-key
    dest: ~/.git-crypt-key
    mode: '0600'

- name: Check if the dotfiles repository exists
  ansible.builtin.stat:
    path: ~/dotfiles/.git
  register: git_dotfiles
     
- name: Clone git dotfiles repo
  ansible.builtin.git:
    repo: 'git@github.com:ftassi/dotfiles.git'
    dest: ~/dotfiles
    update: no
  when: not git_dotfiles.stat.exists

- name: Unlock secrects in dotfiles repo
  ansible.builtin.shell: git-crypt unlock ~/.git-crypt-key
  args:
    chdir: ~/dotfiles
  when: not git_dotfiles.stat.exists
